name: Build Unity APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2021.3.0f1

    - name: Build APK
      uses: game-ci/unity-builder@v2
      with:
        targetPlatform: Android

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: WolfProject-APK
        path: build/Android/*.apk
